moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1_waist
      - joint2_shoulder
      - joint3_elbow
      - joint4_wrist1
      - joint5_wrist2
      - joint6_wrist3

  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - finger_left_joint
      - finger_right_joint

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
