controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint1_waist
      - joint2_shoulder
      - joint3_elbow
      - joint4_wrist1
      - joint5_wrist2
      - joint6_wrist3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - finger_left_joint
      - finger_right_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    gains:
      finger_left_joint: {p: 250.0, i: 0.0, d: 3.0, i_clamp: 0.0}
      finger_right_joint: {p: 250.0, i: 0.0, d: 3.0, i_clamp: 0.0}
